services:
    app:
        build: .
        restart: always
        container_name: app
        ports:
            - '443:443'
        depends_on:
            - mongo

    mongo:
        image: mongo
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db
        command: [mongod]
