name: Build Test

on:
    pull_request:
        types: [opened]
    workflow_dispatch:

jobs:
    ts-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  cache: npm
            - name: Install deps
              run: npm i
            - name: Build
              run: npm run build

    svelte-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  cache: npm
            - name: Change directory
              run: cd ./pages
            - name: Install deps
              run: npm i
            - name: Build
              run: npm run build
